### ISSUE TITLE
Additional search info

### ISSUE THREAD

**Issue by ArtemNaboka** [petr-konopelko/ng-remote-autocomplete#3]
There is no way to pass any additional parameters to the implementation of **get** method of the AutocompleteSourceService interface.

**Comment by petro-konopelko** [comment]
You can definitely import some service into your autocomplete.
But for your handy, I think about providing another Interface with additional parameters and pass these parameters to the autocomplete component in order no to force a user has not necessary implementation and not to break already existing functionality

**Comment by petro-konopelko** [comment]
Added **ParameterizedAutocompleteSourceService** interface to the 1.1.0 version.
Now you can provide one of the implementations of the **ParameterizedAutocompleteSourceService** or **AutocompleteSourceService** interfaces. 
_**NOTE**_: If you provide implementation of the **ParameterizedAutocompleteSourceService** interface then [searchParameters] also must be provided, otherwise autocomplete will throw an Exception
